language: android
android:
  components:
    - build-tools-27.0.2
    - android-27
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
