language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  deploy:
    provider: releases
    file: app/build/outputs/apk/release/app-release-unsigned.apk
    skip_cleanup: true
    on:
      tags: false
    api_key: $GITHUB_OAUTH_TOKEN
